name: GitHub Actions test
run-name: test1
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: npm i
      - run: npm i -g @vscode/vsce
      - run: vsce package
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            hello-extension*.vsix
            LICENSE.txt
            README.md
